apiVersion: v1
kind: Service
metadata:
  name: lakekeeper-pg
  namespace: monitoring
  labels:
    app.kubernetes.io/name: lakekeeper-pg
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lakekeeper-pg
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
