apiVersion: v1
kind: Service
metadata:
  name: k2i
  namespace: monitoring
  labels:
    app.kubernetes.io/name: k2i
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k2i
  ports:
    - port: 8080
      targetPort: health
      name: health
    - port: 9090
      targetPort: metrics
      name: metrics
