apiVersion: v1
kind: Service
metadata:
  name: arroyo
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: arroyo
  ports:
    - port: 8000
      targetPort: 8000
      name: api
