apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trino
  ports:
    - port: 8080
      targetPort: 8080
      name: http
