apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-aggregator
  namespace: monitoring
  labels:
    app.kubernetes.io/name: fluentbit-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit-aggregator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentbit-aggregator
    spec:
      containers:
        - name: fluentbit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:3.4.1
          ports:
            - containerPort: 24224
              name: fluent-forward
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc
            - name: buffers
              mountPath: /var/fluent-bit/buffers
          env:
            - name: S3_BUCKET
              value: "local-logs"
          envFrom:
            - secretRef:
                name: s3-credentials
      volumes:
        - name: config
          configMap:
            name: fluentbit-aggregator-config
        - name: buffers
          emptyDir: {}
