apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-cluster-events
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-cluster-events
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-cluster-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit-cluster-events
subjects:
  - kind: ServiceAccount
    name: fluentbit-cluster-events
    namespace: monitoring
