apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arroyo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/manudiv16/homelab.git
    targetRevision: main
    path: infrastructure/arroyo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
