apiVersion: v1
kind: Service
metadata:
  name: tansu-pg
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tansu-pg
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tansu-pg
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
